spring:
    # thymeleaf:
    #     prefix: classpath:/static/
    datasource:
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        driverClassName: org.postgresql.Driver